[env]

LIBTORCH = { value = "torch/libtorch", relative = true, force = true }
DYLD_LIBRARY_PATH = { value = "torch/libtorch/lib:$DYLD_LIBRARY_PATH", relative = true, force = true  }

[build]
target = "aarch64-apple-darwin"
rustflags = [
    "-C", "link-arg=-std=c++17", 
]